fix omit error

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -338,54 +338,54 @@ jobs:
   #         - { spec: cp314t-win_arm64, runs_on: windows-11-arm }
 
   # windows:
-    needs: [python_sdist, make_windows_matrix]
-    runs-on: ${{ matrix.runs_on || 'windows-2022' }}
-    strategy:
-      fail-fast: false
-      matrix: ${{ fromJSON(needs.make_windows_matrix.outputs.matrix_json) }}
+    # needs: [python_sdist, make_windows_matrix]
+    # runs-on: ${{ matrix.runs_on || 'windows-2022' }}
+    # strategy:
+    #   fail-fast: false
+    #   matrix: ${{ fromJSON(needs.make_windows_matrix.outputs.matrix_json) }}
 
-    steps:
-    - name: fetch sdist artifact
-      id: fetch_sdist
-      uses: actions/download-artifact@v4
-      with:
-        name: ${{ needs.python_sdist.outputs.sdist_artifact_name }}
+    # steps:
+    # - name: fetch sdist artifact
+    #   id: fetch_sdist
+    #   uses: actions/download-artifact@v4
+    #   with:
+    #     name: ${{ needs.python_sdist.outputs.sdist_artifact_name }}
 
-    - name: Install python
-      uses: actions/setup-python@v5
-      with:
-        python-version: 3.x
+    # - name: Install python
+    #   uses: actions/setup-python@v5
+    #   with:
+    #     python-version: 3.x
 
-    - name: build/test wheels
-      id: build
-      env:
-        CIBW_BUILD: ${{ matrix.spec }}
-        CIBW_TEST_REQUIRES: pytest setuptools
-        CIBW_TEST_COMMAND: ${{ matrix.test_cmd || 'python -m pytest {package}/src/c' }}
-        # FIXME: /testing takes ~45min on Windows and has some failures...
-        # CIBW_TEST_COMMAND='python -m pytest {package}/src/c {package}/testing'
-      run: |
-        set -eux
+    # - name: build/test wheels
+    #   id: build
+    #   env:
+    #     CIBW_BUILD: ${{ matrix.spec }}
+    #     CIBW_TEST_REQUIRES: pytest setuptools
+    #     CIBW_TEST_COMMAND: ${{ matrix.test_cmd || 'python -m pytest {package}/src/c' }}
+    #     # FIXME: /testing takes ~45min on Windows and has some failures...
+    #     # CIBW_TEST_COMMAND='python -m pytest {package}/src/c {package}/testing'
+    #   run: |
+    #     set -eux
 
-        mkdir cffi
+    #     mkdir cffi
 
-        tar zxf cffi*.tar.gz --strip-components=1 -C cffi
+    #     tar zxf cffi*.tar.gz --strip-components=1 -C cffi
 
-        python -m pip install --upgrade pip
-        pip install "${{ matrix.cibw_version || 'cibuildwheel' }}"
-        python -m cibuildwheel --output-dir dist cffi
+    #     python -m pip install --upgrade pip
+    #     pip install "${{ matrix.cibw_version || 'cibuildwheel' }}"
+    #     python -m cibuildwheel --output-dir dist cffi
 
-        echo "artifact_name=$(ls ./dist/)" >> "$GITHUB_OUTPUT"
+    #     echo "artifact_name=$(ls ./dist/)" >> "$GITHUB_OUTPUT"
 
-      shell: bash
+    #   shell: bash
 
-    - name: upload artifacts
-      uses: actions/upload-artifact@v4
-      with:
-        name: ${{ steps.build.outputs.artifact_name }}
-        path: dist/*.whl
-        if-no-files-found: error
-      if: ${{ env.skip_artifact_upload != 'true' }}
+    # - name: upload artifacts
+    #   uses: actions/upload-artifact@v4
+    #   with:
+    #     name: ${{ steps.build.outputs.artifact_name }}
+    #     path: dist/*.whl
+    #     if-no-files-found: error
+    #   if: ${{ env.skip_artifact_upload != 'true' }}
 
   merge_artifacts:
     needs: [python_sdist, linux, macos, windows]
